name: Tests

on: 
  push:
    branches: [ main]
  pull_request:
    branches: [ master ]


jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Lint workflow
          uses: snakemake/snakemake-github-action@v1.23.0
          with:
            directory: .
            args: '--lint'

  Testing:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Test without target
          uses: snakemake/snakemake-github-action@v1.23.0
          with:
            directory: '.test/integration'
            args: '--cores 1 --use-conda  --conda-frontend mamba'

        - name: Clean output
          uses: snakemake/snakemake-github-action@v1.23.0
          with:
            directory: '.test/integration'
            args: 'all --delete-all-output --cores 1'

        - name: Test with targets
          uses: snakemake/snakemake-github-action@v1.23.0
          with: 
            directory: '.test/integration'
            args: '--config sample_targets=test_targets.tsv --cores 1 --use-conda --conda-cleanup-pkgs cache'