name: snakemake_test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          snakefile: '../Snakefile'
          args: '--lint'

      - name: WithoutTargets
        uses: snakemake/snakemake-github-action@v1.23.0
        with: 
          directory: '.test/integration'
          snakefile: '../../Snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'

      - name: WithTargets
        uses: snakemake/snakemake-github-action@v1.23.0
        with: 
          directory: '.test/integration'
          snakefile: '../../Snakefile'
          args: '--config sample_targets=test_targets.tsv --cores 1 --use-conda --conda-cleanup-pkgs cache'